### ISSUE TITLE
OEA_py SALT

### ISSUE THREAD

**Issue by bryan-alvaradofusd** [OpenEducationAnalytics/OpenEducationAnalytics#105]
I was wondering should we have a function below get_secret in OEA() that gets the SALT from key vault? Something like: 
```
 def getSALT(self):
        self.SALT = self.get_secret('kv-oea-SALT')
```

**Comment by ivybarley** [comment]
Thanks for the suggestion. This issue has been addressed in v0.7 release of the OEA framework. the OEA_py notebook in v0.7 generates a salt value that can be modified if you want to use a specific salt.
