### ISSUE TITLE
Module Microsoft_Data\Microsoft_Education_Insights_Premium\  missing notebook?

### ISSUE THREAD

**Issue by leonbravo** [OpenEducationAnalytics/OpenEducationAnalytics#110]
The notebook Insights_module_ingestion runs another notebook that is missing or call needs to be renamed

"%run /NEW_Insights_py"       This notebook is not in the branch.

The only thing similar is Insights_py.

**Comment by leonbravo** [comment]
@ivybarley

**Comment by ivybarley** [comment]
Thanks for raising this issue. The missing notebook has been corrected in the new version of the Microsoft Education Insights module. Please fetch the most recent version and re-run the pipelines in Synapse.
