### ISSUE TITLE
Setup Tags on initial configuration

### ISSUE THREAD

**Issue by uayeb25** [OpenEducationAnalytics/OpenEducationAnalytics#12]
.sh has all the logic to create all the components to set up the integral solution; it starts creating different resource groups, Analytikus has policies created to force add tags. It means that an automatic process that creates components into azure can return errors.

**Observation**: We suggest adding some JSON file with defaults tags to be attached to the setup of the new components, for example:

`[
{
"tag_name":"CreatedBy",
"tag_value":"Uayeb Caballero"
}
]`

and finally, we run our command doing something like:

`./setup.sh <unique_suffix> <tags.json>`

**Comment by genegc** [comment]
Thank you for this suggestion Uayeb.
I've gone ahead and added tags to resources in the setup.sh script that you can modify directly as needed.

For now we won't be adding the ability to specify additional tags on the command line - you'll need to manually edit the setup_base_architecture.sh script.
