### ISSUE TITLE
setup.sh errors

### ISSUE THREAD

**Issue by Watto1234** [OpenEducationAnalytics/OpenEducationAnalytics#135]
![Screenshot 2022-09-12 142934](https://user-images.githubusercontent.com/108643237/189587485-4d74d57e-35bc-408c-9c7b-ebeeadb7e9fe.png)
We are running into some issues trying to run the bash setup.sh script in cloudshell. It appears that a folder path might be missing. Could you please let me know if I am missing something?

**Comment by genegc** [comment]
This issue is resolved. Please be sure to pull down the latest from the repo and try again.
Thanks
