### ISSUE TITLE
Missing Prerequisite to add az-cli-ml extension before first deployment

### ISSUE THREAD

**Issue by olyamusok** [OpenEducationAnalytics/OpenEducationAnalytics#15]
setup.sh fails to create all resources if az-cli-ml extension has not been added prior to the run.
mitigation error message is helpful, but would be great to state this in prereqs.

![image](https://user-images.githubusercontent.com/40611069/125834168-ef2685f2-2d9d-46ee-85d3-c3eca626394a.png)

![image](https://user-images.githubusercontent.com/40611069/125834207-b0f21c04-4675-4b1c-a27f-ee8adc278111.png)

**Comment by genegc** [comment]
Thank you for reporting this. @DanielWahlgren ran into this issue as well and submitted a fix for it - which has been committed now.
