### ISSUE TITLE
Database Name

### ISSUE THREAD

**Issue by dawmclem** [OpenEducationAnalytics/OpenEducationAnalytics#3]
I ran through the guide this morning. In the documentation, please update the database name in Power BI to: test_s2_contosoisd.

**Comment by genegc** [comment]
I've fixed the name in the [OpenEduAnalyticsSolutionGuide](https://github.com/microsoft/OpenEduAnalytics/blob/main/docs/OpenEduAnalyticsSolutionGuide.pdf) and updated the screenshot as well.
Thank you.
