### ISSUE TITLE
Unable to open PowerBi Report

### ISSUE THREAD

**Issue by MarchingBug** [OpenEducationAnalytics/OpenEducationAnalytics#35]
I have the latest version of Power BI Desktop installed. After downloading it, when I try to open the report I get a this error message
![image](https://user-images.githubusercontent.com/11653125/133528714-a810d624-00b9-4a9d-a1ba-96649fd32750.png)

**Comment by genegc** [comment]
What version of power bi desktop do you have?
I've verified that it works with the current version: 2.98.542.0 64-bit (October 2021)
