### ISSUE TITLE
Synapse Workspace Creation Error

### ISSUE THREAD

**Issue by dmccallum** [OpenEducationAnalytics/OpenEducationAnalytics#7]
Received following error message running `setup.sh` at revision `05d0a4e8563b92e15314f795d84af74a98c96b1b`

```
--> Creating storage account containers: stage1, stage2, stage3, synapse
{
  "created": true
}
{
  "created": true
}
{
  "created": true
}
{
  "created": true
}
{
  "created": true
}
--> Creating Synapse Workspace: syn-oea-dmoea001
Command group 'synapse' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
ValidationFailed: Workspace request validation failed, check error details for more information
WARNING: Command group 'synapse' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
ERROR: (ResourceNotFound) The Resource 'Microsoft.Synapse/workspaces/syn-oea-dmoea001' under resource group 'rg-oea-dmoea001' was not found. For more details please goto https://aka.ms/ARMResourceNotFoundFix
argument --assignee: expected one argument

TRY THIS:
az role assignment create --assignee 00000000-0000-0000-0000-000000000000 --role "Storage Account Key Operator Service Role" --scope $id
Create a new role assignment for a user, group, or service principal. (autogenerated)

az role assignment create --assignee sp_name --role a_role
Create role assignment for an assignee.

az aks show --name MyManagedCluster --resource-group MyResourceGroup
Show the details for a managed Kubernetes cluster

https://docs.microsoft.com/en-US/cli/azure/role/assignment#az_role_assignment_create
Read more about the command in reference docs
```

Saw a comment from Paul DeSante on Teams chat that he might have run into the same thing. He said "I also needed to register the Microsoft.sql resource provider so that the Synapse workspace could be setup." I haven't checked to see if that addressed my actual issue.

**Comment by samedelstein** [comment]
This issue came up for me as well, along with provisioning for Spark. Both resolved with registering the provider in the subscription.

**Comment by ghost** [comment]
Same for me as well, having an issue during setup related to the Microsoft.Synapse resource being missing in the new resource group when it tries to create the firewall rule and spark pool.

**Comment by genegc** [comment]
Thanks everyone.
I've added info about this error to the wiki: [Customer subscription xyz needs to be registered with Microsoft.Sql resource provider.](https://github.com/microsoft/OpenEduAnalytics/wiki/Setup-Tips#error-customer-subscription-xyz-needs-to-be-registered-with-microsoftsql-resource-provider)
