### ISSUE TITLE
Linux line endings auto-converted to Windows line ending when cloning repo to Windows machine causing setup.sh to fail

### ISSUE THREAD

**Issue by ohheysergio** [OpenEducationAnalytics/OpenEducationAnalytics#97]
If a user wants to use Windows Subsystem for Linux (WSL) to execute setup.sh, the installation will script will fail if the user just executes a Git clone operation against the OpenEduAnalytics repo. The reason for this is that the default git client behavior on Windows is to convert Linux line endings to Windows line endings, as controlled by the following git config parameter:
[Configuring Git to handle line endings](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings)

While it's true that this parameter is under end-user control and will need to be adjusted on their end, it might be worth adding a brief note to the Setup section about this default behavior when cloning the code to Windows machines. The git clone command can be invoked with the following parameters to override the system defaults with regards to line endings:
`git clone --config core.autocrlf=false https://github.com/microsoft/OpenEduAnalytics`

**Comment by genegc** [comment]
Excellent - thanks for this Sergio
