### ISSUE TITLE
OEA Storage Account "Allow Blob public access" set to True, by setup.sh

### ISSUE THREAD

**Issue by ohheysergio** [OpenEducationAnalytics/OpenEducationAnalytics#98]
This is less of an issue, as a consideration, but it might be worth setting the "Allow Blob public access" parameter for the OEA Storage Account to False by default. Doing so would add one more layer of risk mitigation, by forcing end-users to explicitly enable this feature if they really do have a use case for anonymous access in their own containers within their Storage Account.

Configuring the OEA Storage Account defaults in this way would also align with our recommendations in the following document, [Security recommendations for Blob storage](https://docs.microsoft.com/en-us/azure/storage/blobs/security-recommendations) where we outline the following:
> Anonymous public read access to a container and its blobs grants read-only access to those resources to any client. Avoid enabling public read access unless your scenario requires it.

To be clear though, I did see that ALL OEA blob containers themselves are set to Private, which is great.

**Comment by genegc** [comment]
Thanks Sergio - this change is in place.
