### ISSUE TITLE
unable to "Import resources from support files"

### ISSUE THREAD

**Issue by lalitm14** [OpenEducationAnalytics/OpenEducationAnalytics#99]
AS instructed in Step 3.1 in the document "Tutorial for ML pipeline.docx" here, unable to see the command option for the "+" --> Import resources from support files". Hence cannot proceed, please guide to resolve this issue.
![upload support files option not visible](https://user-images.githubusercontent.com/13347805/164896630-039caa77-8e3c-492a-8759-4e88e0c97361.JPG)

**Comment by ivybarley** [comment]
Thanks for raising this issue. Import resources from support files is not an option in Synapse pipeline import at this time so we have updated the assets and docs to reflect this. **Import from pipeline template** will be the best option to use going forward.
